import type { Metadata } from "next";
// import { Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const roboto = localFont({
  src: [
    {
      path: "../font/Roboto-Bold.ttf",
      weight: "700",
      style: "normal"
    },
    {
      path: "../font/Roboto-Regular.ttf",
      weight: "400",
      style: "normal"
    },
  ],
  variable: '--font-roboto'
})

// const roboto = Roboto({
//   subsets: ["vietnamese"],
//   weight: ["100", "200"]
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body>{children}</body>
    </html>
  );
}
